name: Fortify Scan Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fortify-scan:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Fortify CLI (fcli) development release
      - name: Setup Fortify fcli
        uses: fortify/github-action/setup@v3
        with:
          fcli: bootstrapped
        env:
          FCLI_BOOTSTRAP_VERSION: dev_feat.v3.x.create-pr-fcli-action

      # Step 3: Run fcli action run ci
      - name: Run Fortify CI Action
        env:
          SSC_URL: ${{ vars.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_TOKEN: ${{ secrets.SC_SAST_TOKEN }}
          SSC_APPVERSION: ${{ vars.SSC_APPVERSION }}
          AVIATOR_URL: ${{ vars.AVIATOR_URL }}
          AVIATOR_TOKEN: ${{ secrets.AVIATOR_TOKEN }}
          AVIATOR_APP: ${{ vars.AVIATOR_APP }}
          DO_CREATE_PR: ${{ vars.DO_CREATE_PR }}
          DO_PR_COMMENT: ${{ vars.DO_PR_COMMENT }}
          DO_APPLY_REMEDIATIONS: ${{ vars.DO_APPLY_REMEDIATIONS }}
        run: |
          fcli action run ci --debug --log-file=${GITHUB_WORKSPACE}/fcli.log
      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fcli-log-file
          path: ${GITHUB_WORKSPACE}/fcli.log
        
